### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-docs#112]
Been using binaryninja a lot these past few days, and something that I think would be a great addition is a simple bookmark manager to record addresses + comments :smile:

**Comment by psifertex** [comment]
That's a good suggestion. We've been thinking about how to allow better tracking of location in other ways (cookie crumbs, etc), but a simple bookmark manager would be easy to implement.

**Comment by dfraze** [comment]
Duplicate of issue 99?

**Comment by psifertex** [comment]
Good catch.
