### ISSUE TITLE
can't copy instructions from the disassembly view

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-docs#152]
sometimes i like to copy constants, or blocks of instructions to paste into scripts, or chat.

ida and radare2 allow for this, binary ninja only lets me copy an address

**Comment by CryptXor** [comment]
https://github.com/Vector35/binaryninja-docs/issues/117

https://github.com/Vector35/binaryninja-docs/issues/91

**Comment by plafosse** [comment]
This is a duplicate of #91
