### ISSUE TITLE
OSX Application Metadata is wrong

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-docs#154]
Running 1.0.281, Spotlight reports 1.0.273. Right clicking the Application in /Applications, the Version string reads "Copyright (c) 2015-2016 Vector 35 LLC"
<img width="680" alt="screen shot 2016-02-18 at 11 55 32 am" src="https://cloud.githubusercontent.com/assets/3688488/13151149/cb7149c6-d636-11e5-8046-d05a3eaa0765.png">
<img width="434" alt="screen shot 2016-02-18 at 11 55 17 am" src="https://cloud.githubusercontent.com/assets/3688488/13151150/cb8452aa-d636-11e5-8c67-504ecfbac7ce.png">

**Comment by plafosse** [comment]
Fixed in dev
