### ISSUE TITLE
Patch context menu options

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-docs#156]
Would be useful to add an option to jump to a "code cave" so one can easily add changes without having to overwrite bytes in a binary, if you understand what I am asking. Not really sure how to phrase it fully...

**Comment by plafosse** [comment]
This is a planned feature post v1 release. Closing as duplicate of #27

**Comment by CryptXor** [comment]
Ah, totally forgot about that.... :laughing: I suppose that is why an issue tracker exists
