### ISSUE TITLE
cannot rename negative displacements

### ISSUE THREAD

**Issue by I-am-Batman** [Vector35/binaryninja-docs#176]
it's possible to rename the symbol `0x4` in `mov dword [esp+0x4], 0x1337`, however, there's no option to rename `0xc` in  lines like `mov dword [ebp-0xc], 0x1337`. It seems like this offset is not identified as a 'symbol' the way 0x4 is.

**Comment by psifertex** [comment]
Renaming positive displacements is actually a bug itself. The proper fix for both is the forthcoming stack variable feature, though we admittedly hadn't made an issue for yet. It's now #181.
