### ISSUE TITLE
main not detected in "cookbook" from boston key party 2016

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-docs#197]
http://captf.com/2016/bostonkeyparty/01-cookbook/58056c425dc617b65f94a8b558a4699fedf4a9fb.tgz

main isn't auto identified.

**Comment by plafosse** [comment]
Though it is not obvious this is due to our current lack of stack variables.  Since x86 passes the pointer to main on the stack to __libc_start_main on the stack, we fail to identify it properly.  Marking this as duplicate of #181
