### ISSUE TITLE
inline editing the first line of assemble edits the offset of the function instead

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-docs#2]
_From @psifertex on October 28, 2015 13:26_

There's currently no way to in-place edit the first line of the function (though assembling can work).

The function is instead edited with the memory location. 

See screenshot
![screen shot 2015-10-28 at 9 25 55 am](https://cloud.githubusercontent.com/assets/140215/10789787/ee49c4f8-7d55-11e5-9a3e-89c5f966768c.png)

_Copied from original issue: Vector35/binaryninja#53_

**Comment by plafosse** [comment]
Fixed by checking the token type, if its just a CodeSymbolToken go to the next line.
