### ISSUE TITLE
non-deterministic graph layout

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-docs#21]
Edge routing in the graph layout can produce different routes randomly. We should pick one and stick with it.

**Comment by withzombies** [comment]
Also, it should route to the tightest path possible.

Fixing the green line here:
<img width="1490" alt="screen shot 2015-11-10 at 8 25 40 pm" src="https://cloud.githubusercontent.com/assets/4872355/11081410/6702d058-87ea-11e5-9ab4-4e6d656f6809.png">

**Comment by D0ntPanic** [comment]
Fixed in 1.0.278 beta
