### ISSUE TITLE
Binja Linux Fails To Start

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-docs#214]
I started binja, it updated, now wont restart.

```
$ ~/binaryninja/binaryninja
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

I can't do a --version, but I have a sha1sum if it helps you debug:

```
sha1sum ~/binaryninja/binaryninja
d8366572fb715e17eb5596cf183299806288303a  /home/artem/binaryninja/binaryninja
```

**Comment by psifertex** [comment]
What's the base OS? We updated to Qt 5.6.1 in the recent big update, so it's possibly a side-effect of that.

**Comment by artemdinaburg** [comment]
Ubuntu 14.04 64-bit

**Comment by psifertex** [comment]
Do you have `./qt/platforms/libqxcb.so` in your binaryninja folder? 

A quick test updating automatically from build 208 worked fine on a standard desktop 14.04 x64, and I've got the same binary hash. Wondering if maybe an update partially failed? You can test that by re-downloading the beta bundle from the original URL (email me directly if you need it again). 

If that still fails then it's likely something else on the system.

**Comment by psifertex** [comment]
Also, if the fresh download works, would it be possible to get a copy of the original broken directory so I could try some forensics and identify how the updated failed? (aka, please save the original folder when you do the new install)

**Comment by psifertex** [comment]
Found the solution, thanks for find things this. We'll need to include this in the documentation.

The latest installs require `libegl1-mesa-lts-vivid` on 14.04 (it's possible the trusty version works as well, that's untested).
