### ISSUE TITLE
kde incompatibility

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-docs#59]
kubuntu 15.04 appears to be incompatible: 

```
binaryninja$ ./binaryninja 
kf5.kiconthemes: "Theme tree: (Breeze)"
Cannot mix incompatible Qt library (version 0x50401) with this library (version 0x50501)
Aborted (core dumped)
```

**Comment by psifertex** [comment]
Reported working on 15.10. Leaving open in case it's merely a coincidence and they're running at the same system version of QT -- might need a different fix in the future if we ever use a different QT.

**Comment by psifertex** [comment]
Found a better workaround than upgrading to 15.10:
```QT_PLUGIN_PATH=. ./binaryninja```
to launch binary ninja should allow it to still run. 

When we've implemented the installer it will implement a more clean fix.

**Comment by atlas0fd00m** [comment]
work-around:

QT_PLUGIN_PATH=./qt ./binaryninja

btw, this is now affecting me on kubuntu 15.10.  i still have to use this workaround.
