### ISSUE TITLE
Windows Tooltips and alt+tab

### ISSUE THREAD

**Issue by skolor** [Vector35/binaryninja-docs#61]
Alt+tab'ing away when a tooltip is being rendered causes the tooltip to remain onscreen in the other window. 

![image](https://cloud.githubusercontent.com/assets/417998/11106915/f4fe0172-88a6-11e5-8f8d-2476b70be74b.png)

**Comment by soen-vanned** [comment]
Same in OS X 10.10.5 
<img width="1210" alt="screen shot 2015-11-13 at 11 57 25 am" src="https://cloud.githubusercontent.com/assets/1918848/11151925/c2cedcd2-89fd-11e5-8cf5-b885029bffc1.png">

**Comment by plafosse** [comment]
Thanks, the root cause of this is the same as #11
