### ISSUE TITLE
validate length when inline editing

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-docs#68]
When using the inline editor, error when assembling content that is too large and pad when changing to a shorter length

**Comment by plafosse** [comment]
We now pad out the instruction with nops if the new instruction is smaller than the old one. For instruction that are larger, we pad out to the closest instruction boundary.

**Comment by psifertex** [comment]
To clarify, this is fixed in dev -- should be coming out to beta soon.

**Comment by psifertex** [comment]
fixed in 1.0.273 beta
