### ISSUE TITLE
BinaryView subclasses without __init__ crash

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-docs#79]
from binaryninja import *

class FooViewUpdateNotification(BinaryDataNotification):
    def __init__(self, view):
        self.view = view

class FooView(BinaryView):
    name = "Foo"
    
    def __init_(self, data):
        BinaryView.__init__(self, data.file)
        self.notification = FooViewUpdateNotification(self)

    @classmethod
    def is_valid_for_data(self, data):
        return True

    def init(self):
        return True

FooView.register()

This crashes with a NULL dereference.

**Comment by plafosse** [comment]
I just tried this code and failed to repro the NULL dereference. Does this still exist in the lastest build?

**Comment by plafosse** [comment]
Unable to repro, could be fixed.
