### ISSUE TITLE
Symbol parsing is broken

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-docs#83]
DEF CON 2014 Baby's First Heap corruption has broken symbols.

main, do_exit, and sig_alarm_handler all show up at 0x08048a5a in binaryninja. That's not the case in real life.

[baby.zip](https://github.com/Vector35/binaryninja-docs/files/88392/baby.zip)
[Source](https://github.com/legitbs/quals-2014/tree/master/babyfirst-heap)

**Comment by plafosse** [comment]
This is an artifact of us having a missing feature. BN currently doesn't recognize a call to exit as ending a function.  A forthcoming feature will fix this issue. In the meantime it will continue to look broken. Sorry about that.

**Comment by plafosse** [comment]
BTW this will be a great test case for when the feature is implemented. Thanks!
