### ISSUE TITLE
binaryninja\python\binaryninja is empty after an update

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-docs#87]
(INSTALLPATH)binaryninja\python\binaryninja is empty after an update (at least on Windows). No python API for me.

**Comment by CryptXor** [comment]
It is the same for me, but I have python in the path so I am not experiencing any issues currently? I think... :palm_tree:

**Comment by psifertex** [comment]
This is a bug in the Windows build, Python is broken due to a problem in the build. Additionally, armv7 isn't working (again, just on Windows) as well. New update should be out soon with that fix.

**Comment by psifertex** [comment]
This was a problem with 278 that was fixed in 279.
