### ISSUE TITLE
Searching strings

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-docs#93]
Once again, not sure if it is on the to-do list, but can someone please add the ability to search strings xD

**Comment by psifertex** [comment]
String view is now added, and the upcoming search (#41) should round this out.

**Comment by tekwizz123** [comment]
This window does not seem to be coming up for me in the Beta version on a Windows 10 host. Is there some shortcut/menu option that should enable it or am I overlooking something? Can't seem to find it anywhere.

**Comment by psifertex** [comment]
Look in the lower right for the strings view. Then just type to start searching.

**Comment by tekwizz123** [comment]
Perfect, thanks a lot :+1:
