### ISSUE TITLE
Missing mnemonic docs

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-docs#95]
I have noticed (and a very useful feature) that some mnemonic have a tooltip which highlights the function of the opcode. Also noticed some of them are missing!

Here are some that I have found so far:
```
http://x86.renejeschke.de/html/file_module_x86_id_3.html
http://x86.renejeschke.de/html/file_module_x86_id_1.html
http://x86.renejeschke.de/html/file_module_x86_id_2.html
```

**Comment by psifertex** [comment]
Those are just static data flow analysis. For a summary of instructions, please refer to the LLIL view (Options / Low Level IL)
